competition_ids = {
    'Albania': ['ALB1', 'ALB2'],
    'Algeria': ['ALG1'],
    'Andorra': ['AND1', 'AND2'],
    'Angola': ['AN1L'],
    'Argentina': ['AR1N', 'ARG2', 'ARG3'],
    'Armenia': ['ARM1', 'ARM2'],
    'Australia': ['AUS1', ['A2SW', 'A2VI']],
    'Austria': ['A1', 'A2'],
    'Azerbaijan': ['AZ1'],
    'Bangladesh': ['BGD1'],
    'Belgium': ['BE1', 'BE2'],
    'Belarus': ['WER1'],
    'Bolivia': ['BO1A'],
    'Brazil': ['BRA1', 'BRA2'],
    'Bosnia-Herzegovina': ['BOS1'],
    'Bulgaria': ['BU1', 'BU2'],
    'Canada': ['CDN1'],
    'Cambodia': ['KHM1'],
    'Chile': ['CLPD', 'CL2B'],
    'China': ['CSL'],
    'Colombia': ['COL1'],
    'Costa Rica': ['CRPD'],
    'Croatia': ['KR1'],
    'Cyprus': ['ZYP1'],
    'Czech Republic': ['TS1', 'TS2'],
    'Denmark': ['DK1', 'DK2'],
    'Ecuador': ['EL1S'],
    'Egypt': ['EGY1'],
    'El Salvador': ['SL1A'],
    'England': ['GB1', 'GB2', 'GB3', 'GB4'],
    'Faroe Islands': ['FARO'],
    'Fiji': ['FIJ1'],
    'Finland': ['FI1'],
    'France': ['FR1', 'FR2', 'FR3'],
    'Germany': ['L1', 'L2', 'L3'],
    'Ghana': ['GHPL'],
    'Gibraltar': ['GI1'],
    'Greece': ['GR1', 'GRS2'],
    'Georgia': ['GE1N'],
    'Guatemala': ['GU1A'],
    'Honduras': ['HO1A'],
    'Hong Kong, China': ['HGKG'],
    'Hungary': ['UNG1'],
    'Iceland': ['IS1'],
    'India': ['IND1'],
    'Indonesia': ['IN1L'],
    'Islamic Republic of Iran': ['IRN1'],
    'Republic Of Ireland': ['IR1', 'IR2'],
    'Israel': ['ISR1', 'ISR2'],
    'Italy': ['IT1', 'IT2'],
    'Jamaica': ['JPL1'],
    'Japan': ['JAP1', 'JAP2', 'JAP3'],
    'Kazakhstan': ['KAS1'],
    'Kosovo': ['KO1'],
    'Kyrgyz Republic': ['KG1L'],
    'Laos': ['LAO1'],
    'Latvia': ['LET1'],
    'Lithuania': ['LI1'],
    'Luxembourg': ['LUX1'],
    'North Macedonia': ['MAZ1'],
    'Malaysia': ['MYS1'],
    'Malta': ['MAL1'],
    'Mexico': ['MEXA', 'MEX2'],
    'Montenegro': ['MNE1'],
    'Moldova': ['MO1N'],
    'Morocco': ['MAR1'],
    'Mozambique': ['MO1L'],
    'Myanmar': ['MYA1'],
    'Netherlands': ['NL1', 'NL2'],
    'New Zealand': ['NZNL'],
    'Nicaragua': ['NC1A'],
    'Nigeria': ['NPFL'],
    'Northern Ireland': ['NIR1'],
    'Norway': ['NO1', 'NO2'],
    'Oman': ['OM1L'],
    'Panama': ['PN1C'],
    'Paraguay': ['PR1C'],
    'Peru': ['TDeC', 'PER2'],
    'Poland': ['PL1', 'PL2', 'PL2L'],
    'Portugal': ['PO1', 'PO2', 'PT3A'],
    'Romania': ['RO1', 'RO2'],
    'Russia': ['RU1', 'RU2'],
    'San Marino': ['SMR1'],
    'Saudi Arabia': ['SA1'],
    'Scotland': ['SC1', 'SC2'],
    'Serbia': ['SER1'],
    'Singapore': ['SIN1'],
    'Slovakia': ['SLO1', 'SK2'],
    'Slovenia': ['SL1'],
    'South Africa': ['SFA1'],
    'Korea Republic': ['RSK1', 'RSK2'],
    'Spain': ['ES1', 'ES2', ['E3G2', 'E3G1']],
    'Sweden': ['SE1', 'SE2', ['SE3N', 'SE3S']],
    'Switzerland': ['C1', 'C2'],
    'Chinese Taipei': ['TFPL'],
    'Tajikistan': ['TAD1'],
    'Thailand': ['THA1'],
    'Tunisia': ['TUN1'],
    'Turkey': ['TR1', 'TR2'],
    'United Arab Emirates': ['UAE1'],
    'Ukraine': ['UKR1', 'UKR2'],
    'United States': ['MLS1', 'USL', 'USC3'],
    'Uruguay': ['URU1', 'URU2'],
    'Uzbekistan': ['UZ1'],
    'Venezuela': ['VZ1L', 'VN2C'],
    'Vietnam': ['VIE1'],
    'Wales': ['WAL1']
}


youth_competition_ids = {
    'Armenia': ['AR18'],
    'Austria': ['JGD2', 'JGD3'],
    'Brazil': ['CB20', 'SPjr'],
    'Bosnia-Herzegovina': ['BI19', 'BI17'],
    'Croatia': ['CR19'],
    'Czech Republic': ['CZ19'],
    'Denmark': ['DKDL', 'DKDD'],
    'England': ['GB18'],
    'Finland': ['FINJ'],
    'France': ['F19A', 'F19B', 'F19C', 'F19D'],
    'Germany': ['AJ2', 'AJ1', 'AJ3', 'BJ1', 'BJ2', 'BJ3'],
    'Gibraltar': ['G17L'],
    'Greece': ['GR20'],
    'India': ['ID17'],
    'International': ['CLIY'],
    'Italy': ['IJ1', 'IJ2A', 'IJ2B', 'ITJ5', 'ITJ7', 'ITJ4', 'ITJ6'],
    'Japan': ['J18W', 'J18E'],
    'Mexico': ['M23A', 'M23L'],
    'Netherlands': ['211F', '212F', '181F', '181S', '182F', '182S', 'NLBJ', 'NLVB'],
    'Poland': ['PLZJ'],
    'Portugal': ['PT23'],
    'Russia': ['RUJL', 'RU16', 'RU17'],
    'Serbia': ['SB19', 'SB17'],
    'Slovakia': ['SK19'],
    'Slovenia': ['SL19'],
    'Switzerland': ['C191', 'CH17']
}


UEFA = {
    'Albania': 'ALB',
    'Andorra': 'AND',
    'Armenia': 'ARM',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Bosnia-Herzegovina': 'BIH',
    'Bulgaria': 'BUL',
    'Croatia': 'CRO',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Denmark': 'DEN',
    'England': 'ENG',
    'Estonia': 'EST',
    'Faroe Islands': 'FRO',
    'Finland': 'FIN',
    'France': 'FRA',
    'Georgia': 'GEO',
    'Germany': 'GER',
    'Gibraltar': 'GIB',
    'Greece': 'GRE',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Kazakhstan': 'KAZ',
    'Kosovo': 'KOS',
    'Latvia': 'LVA',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Malta': 'MLT',
    'Moldova': 'MDA',
    'Montenegro': 'MNE',
    'Netherlands': 'NED',
    'North Macedonia': 'MKD',
    'Northern Ireland': 'NIR',
    'Norway': 'NOR',
    'Poland': 'POL',
    'Portugal': 'POR',
    'Republic Of Ireland': 'IRL',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'San Marino': 'SMR',
    'Scotland': 'SCO',
    'Serbia': 'SRB',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Switzerland': 'SUI',
    'Turkey': 'TUR',
    'Ukraine': 'UKR',
    'Wales': 'WAL'
}


CONMEBOL = {
    'Argentina': 'ARG',
    'Bolivia': 'BOL',
    'Brazil': 'BRA',
    'Chile': 'CHI',
    'Colombia': 'COL',
    'Ecuador': 'ECU',
    'Paraguay': 'PAR',
    'Peru': 'PER',
    'Uruguay': 'URU',
    'Venezuela': 'VEN'
}


CONCACAF = {
    # North American Zone (NAFU)
    'Canada': 'CAN',
    'Mexico': 'Mex',
    'United States': 'USA',

    # Central American Zone (UNCAF)
    'Belize': 'BLZ',
    'Costa Rica': 'CRC',
    'El Salvador': 'SLV',
    'Guatemala': 'GUA',
    'Honduras': 'HON',
    'Nicaragua': 'NCA',
    'Panama': 'PAN',

    # Caribbean Zone (CFU)
    'Anguilla': 'AIA',
    'Antigua and Barbuda': 'ATG',
    'Aruba': 'ARU',
    'Bahamas': 'BAH',
    'Barbados': 'BRB',
    'Bermuda': 'BER',
    'Bonaire': 'BOE',
    'British Virgin Islands': 'VGB',
    'Cayman Islands': 'CAY',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'French Guiana': 'GUF',
    'Grenada': 'GRN',
    'Guadeloupe': 'GLP',
    'Guyana': 'GUY',
    'Haiti': 'HAI',
    'Jamaica': 'JAM',
    'Martinique': 'MTQ',
    'Montserrat': 'MSR',
    'Puerto Rico': 'PUR',
    'Saint Kitts and Nevis': 'SKN',
    'Saint Lucia': 'LCA',
    'Saint Martin': 'SMN',
    'Saint Vincent and the Grenadines': 'VIN',
    'Sint Maarten': 'SMA',
    'Suriname': 'SUR',
    'Trinidad and Tobago': 'TRI',
    'Turks and Caicos Islands': 'TCA',
    'U.S. Virgin Islands': 'VIR'
}


ACF = {
    # ASEAN Football Federation (AFF)
    'Australia': 'AUS',
    'Brunei Darussalam': 'BRU',
    'Cambodia': 'CAM',
    'Indonesia': 'IDN',
    'Laos': 'LAO',
    'Malaysia': 'MAS',
    'Myanmar': 'MYA',
    'Philippines': 'PHI',
    'Singapore': 'SGP',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Vietnam': 'VIE',

    # Central Asian Football Association (CAFA)
    'Afghanistan': 'AFG',
    'Islamic Republic of Iran': 'IRN',
    'Kyrgyz Republic': 'KGZ',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'Uzbekistan': 'UZB',

    # East Asian Football Federation (EAFF)
    'China': 'CHN',
    'Chinese Taipei': 'TPE',
    'DPR Korea': 'PRK',
    'Guam': 'GUM',
    'Hong Kong, China': 'HKG',
    'Japan': 'JPN',
    'Korea Republic': 'KOR',
    'Macau': 'MAC',
    'Mongolia': 'MNG',
    'Northern Mariana Islands': 'NMI',

    # South Asian Football Federation (SAFF)
    'Bangladesh': 'BAN',
    'Bhutan': 'BHU',
    'India': 'IND',
    'Maldives': 'MDV',
    'Nepal': 'NEP',
    'Pakistan': 'PAK',
    'Sri Lanka': 'SRI',

    # West Asian Football Federation (WAFF)
    'Bahrain': 'BHR',
    'Iraq': 'IRQ',
    'Jordan': 'JOR',
    'Kuwait': 'KUW',
    'Lebanon': 'LBN',
    'Oman': 'OMA',
    'Palestine': 'PLE',
    'Qatar': 'QAT',
    'Saudi Arabia': 'KSA',
    'Syria': 'SYR',
    'United Arab Emirates': 'UAE',
    'Yemen': 'YEM'
}


CAF = {
    # Union of North African Football (UNAF)
    'Algeria': 'ALG',
    'Egypt': 'EGY',
    'Libya': 'LBY',
    'Morocco': 'MAR',
    'Tunisia': 'TUN',

    # West African Football Union (WAFU-UFOA)
    'Benin': 'BEN',
    'Burkina Faso': 'BFA',
    'Cape Verde': 'CPV',
    'Gambia': 'GAM',
    'Ghana': 'GHA',
    'Guinea': 'GUI',
    'Guinea-Bissau': 'GNB',
    'Ivory Coast': 'CIV',
    'Liberia': 'LBR',
    'Mali': 'MLI',
    'Mauritania': 'MTN',
    'Niger': 'NIG',
    'Nigeria': 'NGA',
    'Senegal': 'SEN',
    'Sierra Leone': 'SLE',
    'Togo': 'TOG',

    # Central African Football Federations' Union (UNIFFAC)
    'Cameroon': 'CMR',
    'Central African Republic': 'CAR',
    'Chad': 'CHA',
    'Congo': 'CGO',
    'DR Congo': 'COD',
    'Equatorial Guinea': 'EQG',
    'Gabon': 'GAB',
    'São Tomé and Príncipe': 'STP',

    # Council for East and Central Africa Football Associations (CECAFA)
    'Burundi': 'BDI',
    'Djibouti': 'DJI',
    'Eritrea': 'ERI',
    'Ethiopia': 'ETH',
    'Kenya': 'KEN',
    'Rwanda': 'RWA',
    'Somalia': 'SOM',
    'South Sudan': 'SSD',
    'Sudan': 'SDN',
    'Tanzania': 'TAN',
    'Uganda': 'UGA',
    'Zanzibar': 'ZAN',

    # Council of Southern Africa Football Associations (COSAFA)
    'Angola': 'ANG',
    'Botswana': 'BOT',
    'Comoros': 'COM',
    'Eswatini': 'SWZ',
    'Lesotho': 'LES',
    'Madagascar': 'MAD',
    'Malawi': 'MWI',
    'Mauritius': 'MRI',
    'Mozambique': 'MOZ',
    'Namibia': 'NAM',
    'Seychelles': 'SEY',
    'South Africa': 'RSA',
    'Zambia': 'ZAM',
    'Zimbabwe': 'ZIM',

    # Non-regional members
    'Réunion': 'REU'
}


OCF = {
    'American Samoa': 'ASA',
    'Cook Islands': 'COK',
    'Fiji': 'FIJ',
    'Kiribati': 'KIR',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Papua New Guinea': 'PNG',
    'Samoa': 'SAM',
    'Solomon Islands': 'SOL',
    'Tahiti': 'TAH',
    'Tonga': 'TGA',
    'Tuvalu': 'TUV',
    'Vanuatu': 'VAN'
}


positions = {
    'AM': 'Attacking Midfield',
    'CM': 'Central Midfield',
    'CB': 'Centre-Back',
    'CF': 'Centre-Forward',
    'D': 'Defender',
    'DM': 'Defensive Midfield',
    'GK': 'Goalkeeper',
    'LM': 'Left Midfield',
    'LW': 'Left Winger',
    'LB': 'Left-Back',
    'M': 'Mittelfeld',
    'RM': 'Right Midfield',
    'RW': 'Right Winger',
    'RB': 'Right-Back',
    'SS': 'Second Striker',
    'ST': 'Striker',
    'SW': 'Sweeper'
}




transfermarkt_countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Virgin Islands',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Aruba',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bolivia',
    'Bonaire',
    'Bosnia-Herzegovina',
    'Botsuana',
    'Brazil',
    'British Virgin Islands',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Cayman Islands',
    'Central African Republic'
    'Chad',
    'Chile',
    'China',
    'Chinese Taipei',
    'Colombia',
    'Comoros',
    'Congo',
    'Cookinseln',
    'Costa Rica',
    "Cote d'Ivoire",
    'Croatia',
    'Cuba',
    'Curacao',
    'Cyprus',
    'Czech Republic',
    'DR Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'England'
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Faroe Islands',
    'Fiji',
    'Finland',
    'France',
    'French Guiana',
    'Gabon',
    'Georgia',
    'Germany',
    'Ghana',
    'Gibraltar',
    'Greece',
    'Grenada',
    'Guadeloupe',
    'Guam',
    'Guatemala',
    'Guernsey',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hongkong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Isle of Man',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jersey',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Korea, North',
    'Korea, South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macao',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Mali',
    'Malta',
    'Martinique',
    'Mauritania',
    'Mauritius',
    'Mayotte',
    'Mexico',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Montserrat',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nepal',
    'Netherlands',
    'Neukaledonien',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Northern Ireland',
    'Norway',
    'Oman',
    'Pakistan',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    "People's republic of the Congo",
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Réunion',
    'Saint-Martin',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Scotland',
    'Senegal',
    'Serbia',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'Southern Sudan',
    'Spain',
    'Sri Lanka',
    'St. Kitts & Nevis',
    'St. Lucia',
    'St. Vincent & Grenadinen',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'The Gambia',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Turks- and Caicosinseln',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Wales',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe'
]


def get_countries_info():
    info = []
    all_countries = {**UEFA, **CONMEBOL, **CONCACAF, **ACF, **CAF, **OCF}
    for country, code in all_countries.items():
        tm_name = country if country in transfermarkt_countries else ''
        comps = competition_ids[country] if country in competition_ids else []
        youth = youth_competition_ids[country] if country in youth_competition_ids else []
        info.append({
            'name': country,
            'transfermarkt_name': tm_name,
            'code': code,
            'competitions': comps,
            'youth_competitions': youth
        })
    return info

if __name__ == '__main__':
    info = get_countries_info()


