competition_ids = {
    'Albania': ['ALB1', 'ALB2'],
    'Algeria': ['ALG1'],
    'Andorra': ['AND1', 'AND2'],
    'Angola': ['AN1L'],
    'Argentina': ['AR1N', 'ARG2', 'ARG3'],
    'Armenia': ['ARM1', 'ARM2'],
    'Australia': ['AUS1', 'A2SW', 'A2VI'],
    'Austria': ['A1', 'A2'],
    'Azerbaijan': ['AZ1'],
    'Bangladesh': ['BGD1'],
    'Belgium': ['BE1', 'BE2'],
    'Belarus': ['WER1'],
    'Bolivia': ['BO1A'],
    'Brazil': ['BRA1', 'BRA2'],
    'Bosnia-Herzegovina': ['BOS1'],
    'Bulgaria': ['BU1', 'BU2'],
    'Canada': ['CDN1'],
    'Cambodia': ['KHM1'],
    'Chile': ['CLPD', 'CL2B'],
    'China': ['CSL'],
    'Colombia': ['COL1'],
    'Costa Rica': ['CRPD'],
    'Croatia': ['KR1'],
    'Cyprus': ['ZYP1'],
    'Czech Republic': ['TS1', 'TS2'],
    'Denmark': ['DK1', 'DK2'],
    'Ecuador': ['EL1S'],
    'Egypt': ['EGY1'],
    'El Salvador': ['SL1A'],
    'England': ['GB1', 'GB2', 'GB3', 'GB4'],
    'Faroe Islands': ['FARO'],
    'Fiji': ['FIJ1'],
    'Finland': ['FI1'],
    'France': ['FR1', 'FR2', 'FR3'],
    'Germany': ['L1', 'L2', 'L3'],
    'Ghana': ['GHPL'],
    'Gibraltar': ['GI1'],
    'Greece': ['GR1', 'GRS2'],
    'Georgia': ['GE1N'],
    'Guatemala': ['GU1A'],
    'Honduras': ['HO1A'],
    'Hong Kong': ['HGKG'],
    'Hungary': ['UNG1'],
    'Iceland': ['IS1'],
    'India': ['IND1'],
    'Indonesia': ['IN1L'],
    'Iran': ['IRN1'],
    'Ireland': ['IR1', 'IR2'],
    'Israel': ['ISR1', 'ISR2'],
    'Italy': ['IT1', 'IT2'],
    'Jamaica': ['JPL1'],
    'Japan': ['JAP1', 'JAP2', 'JAP3'],
    'Kazakhstan': ['KAS1'],
    'Kosovo': ['KO1'],
    'Kyrgyzstan': ['KG1L'],
    'Laos': ['LAO1'],
    'Latvia': ['LET1'],
    'Lithuania': ['LI1'],
    'Luxembourg': ['LUX1'],
    'Macedonia': ['MAZ1'],
    'Malaysia': ['MYS1'],
    'Malta': ['MAL1'],
    'Mexico': ['MEXA', 'MEX2'],
    'Montenegro': ['MNE1'],
    'Moldova': ['MO1N'],
    'Morocco': ['MAR1'],
    'Mozambique': ['MO1L'],
    'Myanmar': ['MYA1'],
    'Netherlands': ['NL1', 'NL2'],
    'New Zealand': ['NZNL'],
    'Nicaragua': ['NC1A'],
    'Nigeria': ['NPFL'],
    'Northern Ireland': ['NIR1'],
    'Norway': ['NO1', 'NO2'],
    'Oman': ['OM1L'],
    'Panama': ['PN1C'],
    'Paraguay': ['PR1C'],
    'Peru': ['TDeC', 'PER2'],
    'Poland': ['PL1', 'PL2', 'PL2L'],
    'Portugal': ['PO1', 'PO2', 'PT3A'],
    'Romania': ['RO1', 'RO2'],
    'Russia': ['RU1', 'RU2'],
    'San Marino': ['SMR1'],
    'Saudi Arabia': ['SA1'],
    'Scotland': ['SC1', 'SC2'],
    'Serbia': ['SER1'],
    'Singapore': ['SIN1'],
    'Slovakia': ['SLO1', 'SK2'],
    'Slovenia': ['SL1'],
    'South Africa': ['SFA1'],
    'South Korea': ['RSK1', 'RSK2'],
    'Spain': ['ES1', 'ES2', 'E3G2', 'E3G1'],
    'Sweden': ['SE1', 'SE2', 'SE3N', 'SE3S'],
    'Switzerland': ['C1', 'C2'],
    'Taiwan': ['TFPL'],
    'Tajikistan': ['TAD1'],
    'Thailand': ['THA1'],
    'Tunisia': ['TUN1'],
    'Turkey': ['TR1', 'TR2'],
    'UAE': ['UAE1'],
    'Ukraine': ['UKR1', 'UKR2'],
    'United States': ['MLS1', 'USL', 'USC3'],
    'Uruguay': ['URU1', 'URU2'],
    'Uzbekistan': ['UZ1'],
    'Venezuela': ['VZ1L', 'VN2C'],
    'Vietnam': ['VIE1'],
    'Wales': ['WAL1']
}


UEFA = {
    'Albania': 'ALB',
    'Andorra': 'AND',
    'Armenia': 'ARM',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Bosnia-Herzegovina': 'BIH',
    'Bulgaria': 'BUL',
    'Croatia': 'CRO',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Denmark': 'DEN',
    'England': 'ENG',
    'Estonia': 'EST',
    'Faroe Islands': 'FRO',
    'Finland': 'FIN',
    'France': 'FRA',
    'Georgia': 'GEO',
    'Germany': 'GER',
    'Gibraltar': 'GIB',
    'Greece': 'GRE',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Kazakhstan': 'KAZ',
    'Kosovo': 'KOS',
    'Latvia': 'LVA',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Malta': 'MLT',
    'Moldova': 'MDA',
    'Montenegro': 'MNE',
    'Netherlands': 'NED',
    'North Macedonia': 'MKD',
    'Northern Ireland': 'NIR',
    'Norway': 'NOR',
    'Poland': 'POL',
    'Portugal': 'POR',
    'Republic Of Ireland': 'IRL',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'San Marino': 'SMR',
    'Scotland': 'SCO',
    'Serbia': 'SRB',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Switzerland': 'SUI',
    'Turkey': 'TUR',
    'Ukraine': 'UKR',
    'Wales': 'WAL'
}


subregions = {
    'C-EU': 'Central Europe',
    'E-EU': 'Eastern Europe',
    'N-EU': 'Northern Europe',
    'S-EU': 'Southern Europe',
    'SE-EU': 'Southeast Europe',
    'W-EU': 'Western Europe'
}


CONMEBOL = {
    'Argentina': 'ARG',
    'Bolivia': 'BOL',
    'Brazil': 'BRA',
    'Chile': 'CHI',
    'Colombia': 'COL',
    'Ecuador': 'ECU',
    'Paraguay': 'PAR',
    'Peru': 'PER',
    'Uruguay': 'URU',
    'Venezuela': 'VEN'
}


CONCACAF = {
    # North American Zone (NAFU)
    'Canada': 'CAN',
    'Mexico': 'Mex',
    'United States': 'USA',

    # Central American Zone (UNCAF)
    'Belize': 'BLZ',
    'Costa Rica': 'CRC',
    'El Salvador': 'SLV',
    'Guatemala': 'GUA',
    'Honduras': 'HON',
    'Nicaragua': 'NCA',
    'Panama': 'PAN',

    # Caribbean Zone (CFU)
    'Anguilla': 'AIA',
    'Antigua and Barbuda': 'ATG',
    'Aruba': 'ARU',
    'Bahamas': 'BAH',
    'Barbados': 'BRB',
    'Bermuda': 'BER',
    'Bonaire': 'BOE',
    'British Virgin Islands': 'VGB',
    'Cayman Islands': 'CAY',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'French Guiana': 'GUF',
    'Grenada': 'GRN',
    'Guadeloupe': 'GLP',
    'Guyana': 'GUY',
    'Haiti': 'HAI',
    'Jamaica': 'JAM',
    'Martinique': 'MTQ',
    'Montserrat': 'MSR',
    'Puerto Rico': 'PUR',
    'Saint Kitts and Nevis': 'SKN',
    'Saint Lucia': 'LCA',
    'Saint Martin': 'SMN',
    'Saint Vincent and the Grenadines': 'VIN',
    'Sint Maarten': 'SMA',
    'Suriname': 'SUR',
    'Trinidad and Tobago': 'TRI',
    'Turks and Caicos Islands': 'TCA',
    'U.S. Virgin Islands': 'VIR'
}


ACF = {
    # ASEAN Football Federation (AFF)
    'Australia': 'AUS',
    'Brunei Darussalam': 'BRU',
    'Cambodia': 'CAM',
    'Indonesia': 'IDN',
    'Laos': 'LAO',
    'Myanmar': 'MYA',
    'Philippines': 'PHI',
    'Singapore': 'SGP',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Vietnam': 'VIE',

    # Central Asian Football Association (CAFA)
    'Afghanistan': 'AFG',
    'Islamic Republic of Iran': 'IRN',
    'Kyrgyz Republic': 'KGZ',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'Uzbekistan': 'UZB',

    # East Asian Football Federation (EAFF)
    'China': 'CHN',
    'Chinese Taipei': 'TPE',
    'DPR Korea': 'PRK',
    'Guam': 'GUM',
    'Hong Kong, China': 'HKG',
    'Japan': 'JPN',
    'Korea Republic': 'KOR',
    'Macau': 'MAC',
    'Mongolia': 'MNG',
    'Northern Mariana Islands': 'NMI',

    # South Asian Football Federation (SAFF)
    'Bangladesh': 'BAN',
    'Bhutan': 'BHU',
    'India': 'IND',
    'Maldives': 'MDV',
    'Nepal': 'NEP',
    'Pakistan': 'PAK',
    'Sri Lanka': 'SRI',

    # West Asian Football Federation (WAFF)
    'Bahrain': 'BHR',
    'Iraq': 'IRQ',
    'Jordan': 'JOR',
    'Kuwait': 'KUW',
    'Lebanon': 'LBN',
    'Oman': 'OMA',
    'Palestine': 'PLE',
    'Qatar': 'QAT',
    'Saudi Arabia': 'KSA',
    'Syria': 'SYR',
    'United Arab Emirates': 'UAE',
    'Yemen': 'YEM'
}


CAF = {
    # Union of North African Football (UNAF)
    'Algeria': 'ALG',
    'Egypt': 'EGY',
    'Libya': 'LBY',
    'Morocco': 'MAR',
    'Tunisia': 'TUN',

    # West African Football Union (WAFU-UFOA)
    'Benin': 'BEN',
    'Burkina Faso': 'BFA',
    'Cape Verde': 'CPV',
    'Gambia': 'GAM',
    'Ghana': 'GHA',
    'Guinea': 'GUI',
    'Guinea-Bissau': 'GNB',
    'Ivory Coast': 'CIV',
    'Liberia': 'LBR',
    'Mali': 'MLI',
    'Mauritania': 'MTN',
    'Niger': 'NIG',
    'Nigeria': 'NGA',
    'Senegal': 'SEN',
    'Sierra Leone': 'SLE',
    'Togo': 'TOG',

    # Central African Football Federations' Union (UNIFFAC)
    'Cameroon': 'CMR',
    'Central African Republic': 'CAR',
    'Chad': 'CHA',
    'Congo': 'CGO',
    'DR Congo': 'COD',
    'Equatorial Guinea': 'EQG',
    'Gabon': 'GAB',
    'São Tomé and Príncipe': 'STP',

    # Council for East and Central Africa Football Associations (CECAFA)
    'Burundi': 'BDI',
    'Djibouti': 'DJI',
    'Eritrea': 'ERI',
    'Ethiopia': 'ETH',
    'Kenya': 'KEN',
    'Rwanda': 'RWA',
    'Somalia': 'SOM',
    'South Sudan': 'SSD',
    'Sudan': 'SDN',
    'Tanzania': 'TAN',
    'Uganda': 'UGA',
    'Zanzibar': 'ZAN',

    # Council of Southern Africa Football Associations (COSAFA)
    'Angola': 'ANG',
    'Botswana': 'BOT',
    'Comoros': 'COM',
    'Eswatini': 'SWZ',
    'Lesotho': 'LES',
    'Madagascar': 'MAD',
    'Malawi': 'MWI',
    'Mauritius': 'MRI',
    'Mozambique': 'MOZ',
    'Namibia': 'NAM',
    'Seychelles': 'SEY',
    'South Africa': 'RSA',
    'Zambia': 'ZAM',
    'Zimbabwe': 'ZIM',

    # Non-regional members
    'Réunion': 'REU'
}


OCF = {
    'American Samoa': 'ASA',
    'Cook Islands': 'COK',
    'Fiji': 'FIJ',
    'Kiribati': 'KIR',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Papua New Guinea': 'PNG',
    'Samoa': 'SAM',
    'Solomon Islands': 'SOL',
    'Tahiti': 'TAH',
    'Tonga': 'TGA',
    'Tuvalu': 'TUV',
    'Vanuatu': 'VAN'
}

positions = {
    'Attacking Midfield': 'AM',
    'Central Midfield': 'CM',
    'Centre-Back': 'CB',
    'Centre-Forward': 'CF',
    'Defender': 'D',
    'Defensive Midfield': 'DM',
    'Goalkeeper': 'GK',
    'Left Midfield': 'LM',
    'Left Winger': 'LW',
    'Left-Back': 'LB',
    'Mittelfeld': 'M',
    'Right Midfield': 'RM',
    'Right Winger': 'RW',
    'Right-Back': 'RB',
    'Second Striker': 'SS',
    'Striker': 'ST',
    'Sweeper': 'SW'
}