UEFA = {
    'Albania': 'ALB',
    'Andorra': 'AND',
    'Armenia': 'ARM',
    'Austria': 'AUT',
    'Azerbaijan': 'AZE',
    'Belarus': 'BLR',
    'Belgium': 'BEL',
    'Bosnia-Herzegovina': 'BIH',
    'Bulgaria': 'BUL',
    'Croatia': 'CRO',
    'Cyprus': 'CYP',
    'Czech Republic': 'CZE',
    'Denmark': 'DEN',
    'England': 'ENG',
    'Estonia': 'EST',
    'Faroe Islands': 'FRO',
    'Finland': 'FIN',
    'France': 'FRA',
    'Georgia': 'GEO',
    'Germany': 'GER',
    'Gibraltar': 'GIB',
    'Greece': 'GRE',
    'Hungary': 'HUN',
    'Iceland': 'ISL',
    'Israel': 'ISR',
    'Italy': 'ITA',
    'Kazakhstan': 'KAZ',
    'Kosovo': 'KOS',
    'Latvia': 'LVA',
    'Liechtenstein': 'LIE',
    'Lithuania': 'LTU',
    'Luxembourg': 'LUX',
    'Malta': 'MLT',
    'Moldova': 'MDA',
    'Montenegro': 'MNE',
    'Netherlands': 'NED',
    'North Macedonia': 'MKD',
    'Northern Ireland': 'NIR',
    'Norway': 'NOR',
    'Poland': 'POL',
    'Portugal': 'POR',
    'Republic Of Ireland': 'IRL',
    'Romania': 'ROU',
    'Russia': 'RUS',
    'San Marino': 'SMR',
    'Scotland': 'SCO',
    'Serbia': 'SRB',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Spain': 'ESP',
    'Sweden': 'SWE',
    'Switzerland': 'SUI',
    'Turkey': 'TUR',
    'Ukraine': 'UKR',
    'Wales': 'WAL'
}


CONMEBOL = {
    'Argentina': 'ARG',
    'Bolivia': 'BOL',
    'Brazil': 'BRA',
    'Chile': 'CHI',
    'Colombia': 'COL',
    'Ecuador': 'ECU',
    'Paraguay': 'PAR',
    'Peru': 'PER',
    'Uruguay': 'URU',
    'Venezuela': 'VEN'
}

CONCACAF = {
    # North American Zone (NAFU)
    'Canada': 'CAN',
    'Mexico': 'Mex',
    'United States': 'USA',

    # Central American Zone (UNCAF)
    'Belize': 'BLZ',
    'Costa Rica': 'CRC',
    'El Salvador': 'SLV',
    'Guatemala': 'GUA',
    'Honduras': 'HON',
    'Nicaragua': 'NCA',
    'Panama': 'PAN',

    # Caribbean Zone (CFU)
    'Anguilla': 'AIA',
    'Antigua and Barbuda': 'ATG',
    'Aruba': 'ARU',
    'Bahamas': 'BAH',
    'Barbados': 'BRB',
    'Bermuda': 'BER',
    'Bonaire': 'BOE',
    'British Virgin Islands': 'VGB',
    'Cayman Islands': 'CAY',
    'Cuba': 'CUB',
    'Curaçao': 'CUW',
    'Dominica': 'DMA',
    'Dominican Republic': 'DOM',
    'French Guiana': 'GUF',
    'Grenada': 'GRN',
    'Guadeloupe': 'GLP',
    'Guyana': 'GUY',
    'Haiti': 'HAI',
    'Jamaica': 'JAM',
    'Martinique': 'MTQ',
    'Montserrat': 'MSR',
    'Puerto Rico': 'PUR',
    'Saint Kitts and Nevis': 'SKN',
    'Saint Lucia': 'LCA',
    'Saint Martin': 'SMN',
    'Saint Vincent and the Grenadines': 'VIN',
    'Sint Maarten': 'SMA',
    'Suriname': 'SUR',
    'Trinidad and Tobago': 'TRI',
    'Turks and Caicos Islands': 'TCA',
    'U.S. Virgin Islands': 'VIR'
}



ACF = {
    # ASEAN Football Federation (AFF)
    'Australia': 'AUS',
    'Brunei Darussalam': 'BRU',
    'Cambodia': 'CAM',
    'Indonesia': 'IDN',
    'Laos': 'LAO',
    'Myanmar': 'MYA',
    'Philippines': 'PHI',
    'Singapore': 'SGP',
    'Thailand': 'THA',
    'Timor-Leste': 'TLS',
    'Vietnam': 'VIE',

    # Central Asian Football Association (CAFA)
    'Afghanistan': 'AFG',
    'Islamic Republic of Iran': 'IRN',
    'Kyrgyz Republic': 'KGZ',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'Uzbekistan': 'UZB',

    # East Asian Football Federation (EAFF)
    'China': 'CHN',
    'Chinese Taipei': 'TPE',
    'DPR Korea': 'PRK',
    'Guam': 'GUM',
    'Hong Kong, China': 'HKG',
    'Japan': 'JPN',
    'Korea Republic': 'KOR',
    'Macau': 'MAC',
    'Mongolia': 'MNG',
    'Northern Mariana Islands': 'NMI',

    # South Asian Football Federation (SAFF)
    'Bangladesh': 'BAN',
    'Bhutan': 'BHU',
    'India': 'IND',
    'Maldives': 'MDV',
    'Nepal': 'NEP',
    'Pakistan': 'PAK',
    'Sri Lanka': 'SRI',

    # West Asian Football Federation (WAFF)
    'Bahrain': 'BHR',
    'Iraq': 'IRQ',
    'Jordan': 'JOR',
    'Kuwait': 'KUW',
    'Lebanon': 'LBN',
    'Oman': 'OMA',
    'Palestine': 'PLE',
    'Qatar': 'QAT',
    'Saudi Arabia': 'KSA',
    'Syria': 'SYR',
    'United Arab Emirates': 'UAE',
    'Yemen': 'YEM'
}

CAF = {
    # Union of North African Football (UNAF)
    'Algeria': 'ALG',
    'Egypt': 'EGY',
    'Libya': 'LBY',
    'Morocco': 'MAR',
    'Tunisia': 'TUN',

    # West African Football Union (WAFU-UFOA)
    'Benin': 'BEN',
    'Burkina Faso': 'BFA',
    'Cape Verde': 'CPV',
    'Gambia': 'GAM',
    'Ghana': 'GHA',
    'Guinea': 'GUI',
    'Guinea-Bissau': 'GNB',
    'Ivory Coast': 'CIV',
    'Liberia': 'LBR',
    'Mali': 'MLI',
    'Mauritania': 'MTN',
    'Niger': 'NIG',
    'Nigeria': 'NGA',
    'Senegal': 'SEN',
    'Sierra Leone': 'SLE',
    'Togo': 'TOG',

    # Central African Football Federations' Union (UNIFFAC)
    'Cameroon': 'CMR',
    'Central African Republic': 'CAR',
    'Chad': 'CHA',
    'Congo': 'CGO',
    'DR Congo': 'COD',
    'Equatorial Guinea': 'EQG',
    'Gabon': 'GAB',
    'São Tomé and Príncipe': 'STP',

    # Council for East and Central Africa Football Associations (CECAFA)
    'Burundi': 'BDI',
    'Djibouti': 'DJI',
    'Eritrea': 'ERI',
    'Ethiopia': 'ETH',
    'Kenya': 'KEN',
    'Rwanda': 'RWA',
    'Somalia': 'SOM',
    'South Sudan': 'SSD',
    'Sudan': 'SDN',
    'Tanzania': 'TAN',
    'Uganda': 'UGA',
    'Zanzibar': 'ZAN',

    # Council of Southern Africa Football Associations (COSAFA)
    'Angola': 'ANG',
    'Botswana': 'BOT',
    'Comoros': 'COM',
    'Eswatini': 'SWZ',
    'Lesotho': 'LES',
    'Madagascar': 'MAD',
    'Malawi': 'MWI',
    'Mauritius': 'MRI',
    'Mozambique': 'MOZ',
    'Namibia': 'NAM',
    'Seychelles': 'SEY',
    'South Africa': 'RSA',
    'Zambia': 'ZAM',
    'Zimbabwe': 'ZIM',

    # Non-regional members
    'Réunion': 'REU'
}

OCF = {
    'American Samoa': 'ASA',
    'Cook Islands': 'COK',
    'Fiji': 'FIJ',
    'Kiribati': 'KIR',
    'New Caledonia': 'NCL',
    'New Zealand': 'NZL',
    'Papua New Guinea': 'PNG',
    'Samoa': 'SAM',
    'Solomon Islands': 'SOL',
    'Tahiti': 'TAH',
    'Tonga': 'TGA',
    'Tuvalu': 'TUV',
    'Vanuatu': 'VAN'
}